@extends('admin.layout')
@section('title','Song Management | OpenTune') @section('heading','Song Management')
@section('content')
<div class="mb-6"><h1 class="text-2xl font-bold">Song Management</h1><p class="mt-1 text-sm text-gray-500">Pantau dan moderasi lagu yang diunggah pengguna.</p></div>
<div class="admin-card mb-5 p-5"><h2 class="mb-4 font-semibold">Popular Song</h2><div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">@forelse($songs->getCollection()->take(6) as $song)<a href="{{ route('songs.show',$song) }}" class="min-w-0 text-center"><img class="aspect-square w-full rounded-xl bg-gray-100 object-cover" src="{{ $song->cover_url }}" alt="Cover {{ $song->title }}"><p class="mt-2 truncate text-xs font-semibold">{{ $song->title }}</p><p class="truncate text-[11px] text-gray-400">{{ $song->artist?->name ?? 'Unknown artist' }}</p></a>@empty<p class="text-sm text-gray-400">Belum ada lagu.</p>@endforelse</div></div>
<div class="admin-card p-5"><div class="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 class="font-bold">All Songs <span class="text-sm font-normal text-gray-400">({{ $songs->total() }})</span></h2></div>
<form method="GET" class="mb-5 flex flex-wrap gap-2"><input class="admin-input min-w-[200px] flex-1" name="q" value="{{ $q }}" placeholder="Cari judul, artist, uploader..."><select class="admin-input w-auto min-w-[150px]" name="genre_id"><option value="">Semua genre</option>@foreach($genres as $genre)<option value="{{ $genre->id }}" @selected((string)$genreId===(string)$genre->id)>{{ $genre->name }}</option>@endforeach</select><button class="admin-btn">Cari</button><a class="rounded-lg border px-4 py-2 text-sm" href="{{ route('admin.songs.index') }}">Reset</a></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Judul Lagu</th><th>Artist</th><th>Album</th><th>Genre</th><th>Uploader</th><th>Durasi</th><th>Aksi</th></tr></thead><tbody>@forelse($songs as $song)<tr><td><div class="flex items-center gap-3"><img class="h-10 w-10 rounded-lg object-cover" src="{{ $song->cover_url }}" alt=""><span class="font-semibold">{{ $song->title }}</span></div></td><td>{{ $song->artist?->name ?? '-' }}</td><td>{{ $song->album?->name ?? 'Single' }}</td><td>{{ $song->genre?->name ?? '-' }}</td><td>{{ $song->user?->username ?? '-' }}</td><td>{{ $song->duration_label }}</td><td><div class="flex gap-2"><a class="rounded-md bg-blue-50 px-3 py-1.5 text-xs text-blue-700" href="{{ route('songs.show',$song) }}">Lihat</a><form method="POST" action="{{ route('admin.songs.destroy',$song) }}" onsubmit="return confirm('Hapus lagu ini?')">@csrf @method('DELETE')<button class="rounded-md bg-red-50 px-3 py-1.5 text-xs text-red-600">Hapus</button></form></div></td></tr>@empty<tr><td colspan="7" class="py-8 text-center text-gray-400">Data lagu tidak ditemukan.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $songs->links() }}</div></div>
@endsection
