@extends('admin.layout')
@section('title','User Management | OpenTune') @section('heading','User Management')
@section('content')
<div class="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-2xl font-bold">User Management</h1><p class="mt-1 text-sm text-gray-500">Kelola akun dan role pengguna OpenTune.</p></div><a class="admin-btn" href="{{ route('admin.users.create') }}">＋ Tambah User</a></div>
<div class="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-3">@foreach([['Total User',\App\Models\User::count()],['Administrator',\App\Models\User::where('role','admin')->count()],['Pengguna',\App\Models\User::where('role','user')->count()]] as $stat)<div class="admin-card p-5"><p class="text-sm text-gray-500">{{ $stat[0] }}</p><p class="mt-2 text-2xl font-bold">{{ number_format($stat[1]) }}</p></div>@endforeach</div>
<div class="admin-card p-5">
<form method="GET" class="mb-5 flex flex-wrap gap-2"><input class="admin-input min-w-[220px] flex-1" name="q" value="{{ $q }}" placeholder="Cari username atau email..."><select class="admin-input w-auto min-w-[130px]" name="role"><option value="">Semua role</option><option value="user" @selected($role==='user')>User</option><option value="admin" @selected($role==='admin')>Admin</option></select><button class="admin-btn">Cari</button><a class="rounded-lg border px-4 py-2 text-sm" href="{{ route('admin.users.index') }}">Reset</a></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Pengguna</th><th>Email</th><th>Role</th><th>Lagu</th><th>Album</th><th>Playlist</th><th>Aksi</th></tr></thead><tbody>
@forelse($users as $user)<tr><td class="font-semibold">{{ $user->username }}</td><td>{{ $user->email }}</td><td><span class="admin-pill {{ $user->role==='admin'?'bg-purple-100 text-purple-700':'bg-blue-50 text-blue-700' }}">{{ ucfirst($user->role) }}</span></td><td>{{ $user->songs_count }}</td><td>{{ $user->albums_count }}</td><td>{{ $user->playlists_count }}</td><td><div class="flex gap-2"><a class="rounded-md bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700" href="{{ route('admin.users.edit',$user) }}">Edit</a>@can('delete',$user)<form method="POST" action="{{ route('admin.users.destroy',$user) }}" onsubmit="return confirm('Hapus akun {{ addslashes($user->username) }}?')">@csrf @method('DELETE')<button class="rounded-md bg-red-50 px-3 py-1.5 text-xs font-semibold text-red-600">Hapus</button></form>@endcan</div></td></tr>@empty<tr><td colspan="7" class="py-8 text-center text-gray-400">Data pengguna tidak ditemukan.</td></tr>@endforelse
</tbody></table></div><div class="mt-5">{{ $users->links() }}</div></div>
@endsection
